# NB: this file was automatically generated by Dynare
#     from RBC_CME_basic.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(7, 6);
gp = zeros(7, 7, 6);
end
return (rp, gp)
end
