# NB: this file was automatically generated by Dynare
#     from RBC_CME_basic.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[3]=((1/params[1]-(1-params[2]))/params[3])^(1/(params[3]-1));
    ys_[1]=ys_[3]^params[3];
    ys_[2]=ys_[1]-params[2]*ys_[3];
    ys_[6]=1/params[1];
    ys_[7]=params[6];
    ys_[4]=1;
    ys_[5]=0;
    # Auxiliary equations
end
end
